
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavigationSidebar from './components/navigationSidebar'
import SearchSidebar from './components/searchSidebar'
import Head from 'next/head'
import { SessionProvider } from 'next-auth/react'
import getCurrentUser from "./actions/getCurrentUser";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentUser = await getCurrentUser()

  return (
    <html lang="en">
      <body className="">
        <div className="w-4/5 m-auto ">
          <div className='flex justify-between'>
              <NavigationSidebar currentUser={currentUser} />
                {children}
              <SearchSidebar currentUser={currentUser} />
          </div>
        </div>
      </body>
    </html>
  )
}
