'use client'

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavigationSidebar from './components/navigationSidebar'
import SearchSidebar from './components/searchSidebar'
import Head from 'next/head'
import { SessionProvider } from 'next-auth/react'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="">
        <div className="w-4/5 m-auto ">
          <div className='flex justify-between'>
            <SessionProvider>
              <NavigationSidebar />
                {children}
              <SearchSidebar />
            </SessionProvider>
          </div>
        </div>
      </body>
    </html>
  )
}
